### ISSUE TITLE
Can not get the depth image through TCP Client/Server

### ISSUE THREAD

**Issue by suzi-soohyun** [petergu684/HoloLens2-ResearchMode-Unity#16]
Hello everybody!

I tested the TCP client/server codes which are recently added.
But the problem is, I can not see any depth image in pc through TCP server.
It's just a 'data' folder and no files in there when I running the Hololens app. (Sensor streaming is alright.)

Did I miss any steps? Or should I edit some parts of the scripts?
If anybody knows the solution, please let me know. Thank you!

**Comment by petergu684** [comment]
You need to change the ip address in the TCPClient script in Unity to your laptop's IP address and make sure your laptop and HoloLens are in the same network. There should be some message printed on the python side once it receives images from HoloLens.

**Comment by suzi-soohyun** [comment]
@petergu684 
![image](https://user-images.githubusercontent.com/72331202/126258311-6ca482d1-8e97-4470-b908-151597d26851.png)

I can see the connected message but can not save the images in the "data" folder.
Is this a network problem also?

**Comment by petergu684** [comment]
Then the network should be fine. On the HoloLens side, you need to click Space button to send images to laptop (see KeyboardCommand.cs). You can do this through Device Portal, or connect a wireless keyboard to HoloLens, or add a button and set the onClick event to the specific function you want to call.

**Comment by suzi-soohyun** [comment]
![image](https://user-images.githubusercontent.com/72331202/126423198-d4efb516-0401-4dce-878c-af82f1360fe3.png)

Virtual keyboard in the Device portal was not working so I made a button for the function call to save the depth images.
And now it worked! Thank you so much :)

**Comment by AnandMulay** [comment]
@suzi-soohyun did you changed anything in the Python file, I just added the localhost IP in python and added my laptop IP in unity with the same port 9090 but the connection is not happening
