### ISSUE TITLE
Long throw sensor Point Cloud?

### ISSUE THREAD

**Issue by vbandi** [petergu684/HoloLens2-ResearchMode-Unity#18]
Hi,

I'd like to request a way to get the point cloud for the long throw sensor. I had a look at HL2ResearchMode::DepthSensorLoop, and I think I found where to do it, but I'm not a C++ dev and can barely understand what's going on. The code seems to be written around the short throw sensor, and thus modifying it to include the long throw sensor for point cloud is beyond what I'm able to do. 

I understand that the key is to use MapImagePointToCameraUnityPlane, which also exists for the long depth sensor.

**Comment by Zulex** [comment]
@vbandi 
Did you manage to do this? I have the exact same issue.

**Comment by vbandi** [comment]
@Zulex nope.

**Comment by petergu684** [comment]
I may try to do it later but I suppose it should be pretty similar to the short throw one?

**Comment by petergu684** [comment]
Added :)

**Comment by vbandi** [comment]
@petergu684 yohooo! I'll check it soon.

**Comment by vbandi** [comment]
Thanks! Works well, submitted a PR with a small fix. I see some crashes in my app when turning off the depth sensor altogether, but couldn't find the cause yet.

**Comment by Sindhu2k3** [comment]
> Hi,
> 
> I'd like to request a way to get the point cloud for the long throw sensor. I had a look at HL2ResearchMode::DepthSensorLoop, and I think I found where to do it, but I'm not a C++ dev and can barely understand what's going on. The code seems to be written around the short throw sensor, and thus modifying it to include the long throw sensor for point cloud is beyond what I'm able to do.
> 
> I understand that the key is to use MapImagePointToCameraUnityPlane, which also exists for the long depth sensor.

I am facing the same issue. if the problem is solved could you please guide me through it
