### ISSUE TITLE
Can I get RGB-D data with this repo?

### ISSUE THREAD

**Issue by euijaebilly** [petergu684/HoloLens2-ResearchMode-Unity#21]
Thank you very much for your hard work.

I want to get RGB-D data using HoloLens 2.
In the official repo, separately stored data is processed using Python and then data is created.
But I want to get RGB-D data from the device and store it frame by frame.

The most similar thing I found is
https://github.com/cyberj0g/HoloLensForCV
https://github.com/doughtmw/HoloLensForCV-Unity

**Comment by euijaebilly** [comment]
What I need is to make the depth data displayed as a curved surface into a flat image, and find a region within it that matches the color image.

**Comment by petergu684** [comment]
Mapping between RGB image and depth image is not implemented in this repo. The second repo you mentioned (https://github.com/doughtmw/HoloLensForCV-Unity) have the implementation you need on HoloLens 1. Probably you could refer to that and try to do that yourself :)
