### ISSUE TITLE
VLC GetTimeStamp wrong Camera Frame ?

### ISSUE THREAD

**Issue by rowvn** [petergu684/HoloLens2-ResearchMode-Unity#24]
Not sure, but shouldnt it be:

In **void HL2ResearchMode::SpatialCamerasFrontLoop(HL2ResearchMode* pHL2ResearchMode)**

_Is:_
ResearchModeSensorTimestamp timestamp_left, timestamp_right;
pLFCameraFrame->GetTimeStamp(&timestamp_left);
**pLFCameraFrame**->GetTimeStamp(&timestamp_right);

_Should be:_
ResearchModeSensorTimestamp timestamp_left, timestamp_right;
pLFCameraFrame->GetTimeStamp(&timestamp_left);
**pRFCameraFrame**->GetTimeStamp(&timestamp_right);

**Comment by petergu684** [comment]
Haha yes you are right. Just fixed it. Thanks for pointing this out. :)
