### ISSUE TITLE
namespace can not be found in unity script

### ISSUE THREAD

**Issue by mahdidBagheri** [petergu684/HoloLens2-ResearchMode-Unity#40]
![photo_2022-04-02_08-53-47](https://user-images.githubusercontent.com/43098361/161366158-81b5ef23-e278-492e-a598-ed0f6ced2c2d.jpg)

Hi. Thank you for good repo.
I want to use this plugin in my own project, but script in unity can not find plugin namespace even though I followed the instruction (builed in Release/ARM64 copied .dll & .winmd to Assets/Plugins/WSA/ARM64). did I missed sth or it needs further configuration?

**Comment by anjelomerte** [comment]
Hey, curious how you got it working. Currently trying to figure that out as well. Any help much appreciated:)

**Comment by mahdidBagheri** [comment]
Actually I really can't remember. I think I didn't. Just cloned the repo and trimmed unwanted parts and developed based on it. :)
