### ISSUE TITLE
Can't connect the HoloLens 2 to the python server

### ISSUE THREAD

**Issue by mattsiel** [petergu684/HoloLens2-ResearchMode-Unity#49]
What steps would I take to connect a HoloLens 2 to the python server?

I currently am doing:
building and running the application:
starting the python script:
pressing the "Connect to Network button" on the app menu on the HoloLens 2:

**Comment by kookoo9999** [comment]
Did you solve this problem? 
I'am having same problem, so if you sovle this , can you tell me ??
