### ISSUE TITLE
Accuracy of HoloLens2 Depth Camera

### ISSUE THREAD

**Issue by camroo29** [petergu684/HoloLens2-ResearchMode-Unity#61]
Hi,

I faced some accuracy issues with the output of the Depth Camera. I am trying to project point cloud on the object after taking a snapshot with the depth camera. The point cloud is projected about a few (2-4) cm under the real surface. XY are projected perfectly but the real depth seems to have some issue. I tried multiple types of objects. But there seems of an offset for the depth. An [issue](https://github.com/microsoft/HoloLens2ForCV/issues/55) was opened but there have not been many updates there. 

Has anyone faced such an issue and how did you resolve it? 

Thanks

**Comment by petergu684** [comment]
Thanks for bringing it up. Please refer to my response in the original [issue](https://github.com/microsoft/HoloLens2ForCV/issues/55). I am closing this one.
