### ISSUE TITLE
Saving results

### ISSUE THREAD

**Issue by ozgunkaratas** [petergu684/HoloLens2-ResearchMode-Unity#9]
Hello everybody!

has anybody implemented some code to save the data obtained from sensors to a file? I would appreciate some tips regarding this matter,

thanks a lot!

**Comment by petergu684** [comment]
Have you tried [official example of Stream Recorder](https://github.com/microsoft/HoloLens2ForCV/tree/main/Samples/StreamRecorder)? This works pretty well for me.
